Deploy All Docs Github Action (#1031)
<!--
Thank you for opening a pull request!

Please add a brief description of the proposed change here.
Also, please tick the appropriate points in the checklist below.
-->

## Motivation and Context
<!-- Why is this change needed? What problem does it solve? -->
This PR introduces CI workflow for documentation release purposes. Also
it introduces guardrail to avoid running these documentation jobs from
develop, because you almost never want it - you want to deploy
documentation from latest release branch. BUT IF YOU REALLY WANT TO RUN
IT FROM DEVELOP - you can just create branch from develop and run it
from there.

Also I removed push-to-main workflow because it does not make sense
anymore.
## Breaking Changes
<!-- Will users need to update their code or configurations? -->

---

#### Type of the changes
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Documentation update
- [ ] Tests improvement
- [x] Refactoring

#### Checklist
- [x] The pull request has a description of the proposed change
- [x] I read the [Contributing
Guidelines](https://github.com/JetBrains/koog/blob/main/CONTRIBUTING.md)
before opening the pull request
- [x] The pull request uses **`develop`** as the base branch
- [x] Tests for the changes have been added
- [ ] All new and existing tests passed

##### Additional steps for pull requests adding a new feature
- [ ] An issue describing the proposed change exists
- [ ] The pull request includes a link to the issue
- [ ] The change was discussed and approved in the issue
- [ ] Docs have been added / updated

diff --git a/.github/workflows/deploy-dokka-docs.yml b/.github/workflows/deploy-dokka-docs.yml
--- a/.github/workflows/deploy-dokka-docs.yml
+++ b/.github/workflows/deploy-dokka-docs.yml
@@ -4,6 +4,16 @@ on:
   workflow_dispatch:  # Manual trigger
 
 jobs:
+  check-branch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fail if running on blocked branch
+        if: |
+          github.ref == 'refs/heads/develop'
+        run: |
+          echo "This workflow cannot be run on develop branch. If you want to deploy docs, run it on the latest release branch"
+          exit 1
+
   deploy:
     runs-on: ubuntu-latest
     env:
